name: Building

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: docker login -u ygorcalimanis -p dckr_pat_y9XnmBYwnCIPlce8JV_a7uMKUpA
    - name: docker image
      run: docker build -t ygorcalimanis/study-api .
    - name: push to docker
      run: docker push ygorcalimanis/study-api
